#!/usr/bin/env bash

bundle install --deployment --path vendor/bundle --without development

npm install --no-progress
npm rebuild --no-progress

npm install chromedriver ngrok --no-progress
PATH=$PATH:`pwd`/node_modules/ngrok/bin:`pwd`/node_modules/chromedriver/bin/

bundle exec rake
